### ISSUE TITLE
安卓windscribe登录总是无法连接上

### ISSUE THREAD

**Issue by wang-muhuo** [carolcoral/free_vpn#5]

**Comment by peterGGone** [comment]
电脑也连不上，好像凉了

**Comment by carolcoral** [comment]
来至官网的解答：
There could be many reasons why you're unable to connect to a server or it disconnects randomy, these may include but are not limited to:

    1.Software on your computer preventing Windscribe from connecting. This may include anti-virus, anti-malware or personal firewalls.
    2.Network that you're on is blocking or interfering with VPN connections. This may include school and corporate networks.
    3.Your Internet may be too slow.
    4.It's the full moon.
See the Slow Speeds guide as the solutions there will be applicable in this case. 

If all else fails, please make a connection attempt, wait 2 minutes, make sure you have Internet connectivity (disconnect if you don't) and then go into Preferences, in the Debug tab, click "Send Log", then create a support ticket so we could have a look. If the log fails to send, click "View Log" and copy/paste the log into the support ticket.

**Comment by carolcoral** [comment]
# Slow speeds

Internet routing is imperfect by nature, as there are many factors that can dictate speeds, at various times of the day. Here are some things you can do to improve speeds. 

### 1. Connect to the closest location
To get the best speeds you should connect to the closest location to you, geographically. Keep in mind that you can expand each location to reveal a list of cities by clicking the arrow to the right of the location name in the drop down menu.

### 2. Try a different port or protocol
If you don't have Windscribe v1.81 installed, please download + install the latest version from our website. Then switch to the "IKEv2" protocol. You can do this by going into Preferences -> Connection inside the Windscribe application. If this has no effect, try the Stealth protocol. Try experiempting with random ports. Some ports may work better than others on highly restrictvie networks. 

### 3. Disable anti-virus/firewall
Some modern anti-virus/firewall software does a lot more than just protect you from malware. Products like Avira, Kaspersky and some others inspect your network traffic in order to do their job. This can sometimes cause the connection to our servers to be slowed down or interrupted entirely, which will result in slow speeds and frequent disconnects. You should try exiting this type of software entirely, as even pausing protection will sometimes have no effect. 

### 4. Enable VPN pass-through
If you have access to the router on your network, look for "IPSec/IKEv2/VPN pass-through" option on the router configuration page. Make sure it's enabled.

**Comment by carolcoral** [comment]
@peterGGone 经过测试，电脑端可以先链接“紧急链接”后再登录使用，链接时间比较长，每种我大概等待了3分钟

**Comment by carolcoral** [comment]
@wang-muhuo 安卓端确实凉了，不过可以直接使用教程中的过渡VPN的那个软件

**Comment by SparkUI20180824** [comment]
说实话啊，确实连不上，所有协议都不行

**Comment by carolcoral** [comment]
> 说实话啊，确实连不上，所有协议都不行

是的，后面我都基本上只更新SS了，这个很稳定，目前用都没问题
